import { documentDirectory } from "expo-file-system";
import { PentagramPreference, Section } from "./types";

export const DOCUMENT_DIRECTORY = `${documentDirectory}storage/`;
export const SCORE_PHOTO_RATIO = 3.5;
export const FILENAME_SONGS = "songs.json";
export const FILENAME_CONCERTS = "concerts.json";
export const FILENAME_SETTINGS = "settings.json";

export const SECTIONS = [
  "tenori",
  "baritoni",
  "bassi",
  "soprani",
  "mezzosoprani",
  "contralti",
] as const;

export const NOTES = ["C", "D", "E", "F", "G", "A", "B"] as const;

export const NOTE_NAMES: Record<(typeof NOTES)[number], string> = {
  C: "Do",
  D: "Re",
  E: "Mi",
  F: "Fa",
  G: "Sol",
  A: "La",
  B: "Si",
};

export const NOTEFILES = {
  synth0B: require("../assets/notes/synth/0B.mp3"),
  synth1C: require("../assets/notes/synth/1C.mp3"),
  synth1CD: require("../assets/notes/synth/1CD.mp3"),
  synth1D: require("../assets/notes/synth/1D.mp3"),
  synth1DE: require("../assets/notes/synth/1DE.mp3"),
  synth1E: require("../assets/notes/synth/1E.mp3"),
  synth1F: require("../assets/notes/synth/1F.mp3"),
  synth1FG: require("../assets/notes/synth/1FG.mp3"),
  synth1G: require("../assets/notes/synth/1G.mp3"),
  synth1GA: require("../assets/notes/synth/1GA.mp3"),
  synth1A: require("../assets/notes/synth/1A.mp3"),
  synth1AB: require("../assets/notes/synth/1AB.mp3"),
  synth1B: require("../assets/notes/synth/1B.mp3"),
  synth2C: require("../assets/notes/synth/2C.mp3"),
  synth2CD: require("../assets/notes/synth/2CD.mp3"),
  synth2D: require("../assets/notes/synth/2D.mp3"),
  synth2DE: require("../assets/notes/synth/2DE.mp3"),
  synth2E: require("../assets/notes/synth/2E.mp3"),
  synth2F: require("../assets/notes/synth/2F.mp3"),
  synth2FG: require("../assets/notes/synth/2FG.mp3"),
  synth2G: require("../assets/notes/synth/2G.mp3"),
  synth2GA: require("../assets/notes/synth/2GA.mp3"),
  synth2A: require("../assets/notes/synth/2A.mp3"),
  synth2AB: require("../assets/notes/synth/2AB.mp3"),
  synth2B: require("../assets/notes/synth/2B.mp3"),
  synth3C: require("../assets/notes/synth/3C.mp3"),
  synth3CD: require("../assets/notes/synth/3CD.mp3"),
  synth3D: require("../assets/notes/synth/3D.mp3"),
  synth3DE: require("../assets/notes/synth/3DE.mp3"),
  synth3E: require("../assets/notes/synth/3E.mp3"),
  synth3F: require("../assets/notes/synth/3F.mp3"),
  synth3FG: require("../assets/notes/synth/3FG.mp3"),
  synth3G: require("../assets/notes/synth/3G.mp3"),
  synth3GA: require("../assets/notes/synth/3GA.mp3"),
  synth3A: require("../assets/notes/synth/3A.mp3"),
  synth3AB: require("../assets/notes/synth/3AB.mp3"),
  synth3B: require("../assets/notes/synth/3B.mp3"),
  synth4C: require("../assets/notes/synth/4C.mp3"),
  synth4CD: require("../assets/notes/synth/4CD.mp3"),
  synth4D: require("../assets/notes/synth/4D.mp3"),
  synth4DE: require("../assets/notes/synth/4DE.mp3"),
  synth4E: require("../assets/notes/synth/4E.mp3"),
  synth4F: require("../assets/notes/synth/4F.mp3"),
  synth4FG: require("../assets/notes/synth/4FG.mp3"),
  synth4G: require("../assets/notes/synth/4G.mp3"),
  synth4GA: require("../assets/notes/synth/4GA.mp3"),
  synth4A: require("../assets/notes/synth/4A.mp3"),
  synth4AB: require("../assets/notes/synth/4AB.mp3"),
  synth4B: require("../assets/notes/synth/4B.mp3"),
  synth5C: require("../assets/notes/synth/5C.mp3"),
  synth5CD: require("../assets/notes/synth/5CD.mp3"),
  synth5D: require("../assets/notes/synth/5D.mp3"),
  synth5DE: require("../assets/notes/synth/5DE.mp3"),
  synth5E: require("../assets/notes/synth/5E.mp3"),
  synth5F: require("../assets/notes/synth/5F.mp3"),
  synth5FG: require("../assets/notes/synth/5FG.mp3"),
  synth5G: require("../assets/notes/synth/5G.mp3"),
  synth5GA: require("../assets/notes/synth/5GA.mp3"),
  synth5A: require("../assets/notes/synth/5A.mp3"),
  synth5AB: require("../assets/notes/synth/5AB.mp3"),
  synth5B: require("../assets/notes/synth/5B.mp3"),
  synth6C: require("../assets/notes/synth/6C.mp3"),
  pluck0B: require("../assets/notes/pluck/0B.mp3"),
  pluck1C: require("../assets/notes/pluck/1C.mp3"),
  pluck1CD: require("../assets/notes/pluck/1CD.mp3"),
  pluck1D: require("../assets/notes/pluck/1D.mp3"),
  pluck1DE: require("../assets/notes/pluck/1DE.mp3"),
  pluck1E: require("../assets/notes/pluck/1E.mp3"),
  pluck1F: require("../assets/notes/pluck/1F.mp3"),
  pluck1FG: require("../assets/notes/pluck/1FG.mp3"),
  pluck1G: require("../assets/notes/pluck/1G.mp3"),
  pluck1GA: require("../assets/notes/pluck/1GA.mp3"),
  pluck1A: require("../assets/notes/pluck/1A.mp3"),
  pluck1AB: require("../assets/notes/pluck/1AB.mp3"),
  pluck1B: require("../assets/notes/pluck/1B.mp3"),
  pluck2C: require("../assets/notes/pluck/2C.mp3"),
  pluck2CD: require("../assets/notes/pluck/2CD.mp3"),
  pluck2D: require("../assets/notes/pluck/2D.mp3"),
  pluck2DE: require("../assets/notes/pluck/2DE.mp3"),
  pluck2E: require("../assets/notes/pluck/2E.mp3"),
  pluck2F: require("../assets/notes/pluck/2F.mp3"),
  pluck2FG: require("../assets/notes/pluck/2FG.mp3"),
  pluck2G: require("../assets/notes/pluck/2G.mp3"),
  pluck2GA: require("../assets/notes/pluck/2GA.mp3"),
  pluck2A: require("../assets/notes/pluck/2A.mp3"),
  pluck2AB: require("../assets/notes/pluck/2AB.mp3"),
  pluck2B: require("../assets/notes/pluck/2B.mp3"),
  pluck3C: require("../assets/notes/pluck/3C.mp3"),
  pluck3CD: require("../assets/notes/pluck/3CD.mp3"),
  pluck3D: require("../assets/notes/pluck/3D.mp3"),
  pluck3DE: require("../assets/notes/pluck/3DE.mp3"),
  pluck3E: require("../assets/notes/pluck/3E.mp3"),
  pluck3F: require("../assets/notes/pluck/3F.mp3"),
  pluck3FG: require("../assets/notes/pluck/3FG.mp3"),
  pluck3G: require("../assets/notes/pluck/3G.mp3"),
  pluck3GA: require("../assets/notes/pluck/3GA.mp3"),
  pluck3A: require("../assets/notes/pluck/3A.mp3"),
  pluck3AB: require("../assets/notes/pluck/3AB.mp3"),
  pluck3B: require("../assets/notes/pluck/3B.mp3"),
  pluck4C: require("../assets/notes/pluck/4C.mp3"),
  pluck4CD: require("../assets/notes/pluck/4CD.mp3"),
  pluck4D: require("../assets/notes/pluck/4D.mp3"),
  pluck4DE: require("../assets/notes/pluck/4DE.mp3"),
  pluck4E: require("../assets/notes/pluck/4E.mp3"),
  pluck4F: require("../assets/notes/pluck/4F.mp3"),
  pluck4FG: require("../assets/notes/pluck/4FG.mp3"),
  pluck4G: require("../assets/notes/pluck/4G.mp3"),
  pluck4GA: require("../assets/notes/pluck/4GA.mp3"),
  pluck4A: require("../assets/notes/pluck/4A.mp3"),
  pluck4AB: require("../assets/notes/pluck/4AB.mp3"),
  pluck4B: require("../assets/notes/pluck/4B.mp3"),
  pluck5C: require("../assets/notes/pluck/5C.mp3"),
  pluck5CD: require("../assets/notes/pluck/5CD.mp3"),
  pluck5D: require("../assets/notes/pluck/5D.mp3"),
  pluck5DE: require("../assets/notes/pluck/5DE.mp3"),
  pluck5E: require("../assets/notes/pluck/5E.mp3"),
  pluck5F: require("../assets/notes/pluck/5F.mp3"),
  pluck5FG: require("../assets/notes/pluck/5FG.mp3"),
  pluck5G: require("../assets/notes/pluck/5G.mp3"),
  pluck5GA: require("../assets/notes/pluck/5GA.mp3"),
  pluck5A: require("../assets/notes/pluck/5A.mp3"),
  pluck5AB: require("../assets/notes/pluck/5AB.mp3"),
  pluck5B: require("../assets/notes/pluck/5B.mp3"),
  pluck6C: require("../assets/notes/pluck/6C.mp3"),
} as const;
export const PENTAGRAM_PREFERENCE: Record<Section, PentagramPreference> = {
  soprani: "high",
  mezzosoprani: "high",
  contralti: "low",
  tenori: "high",
  baritoni: "low",
  bassi: "low",
};
